name: Push latest
on:
  push:
    branches:
      - develop
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: docker build --tag nepolin/neplatform:latest --tag nepolin/neplatform:${GITHUB_SHA:0:4} .
    - name: Verifica el formato
      run: docker run nepolin/neplatform:latest make check
    - name: Corre pruebas y evalúa cobertura
      run: docker run nepolin/neplatform:latest make coverage
    - name: Evalúa resistencia a mutaciones
      run: docker run nepolin/neplatform:latest make mutants
    - name: Docker log-in
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
    - name: Sube latest a Docker Hub
      run: docker push nepolin/neplatform:latest
    - name: Sube sha a Docker Hub
      run: docker push nepolin/neplatform:${GITHUB_SHA:0:4}
